### ISSUE TITLE
Not working on Mozilla Firefox?

### ISSUE THREAD

**Issue by mautematico** [ummjackson/uber-data-extractor#3]

**Comment by ummjackson** [comment]
Hi there! Have you tried disabling all extensions/plugins, restarting the browser and then trying again? There are a lot of plugins that might accidentally stop the bookmarklet from working (namely ad blockers). 

What happens when it does not work? Does it give you a message that says it's scraping? Does it download a file? Is the file blank?

Additionally, can you please let me know:

- Operating System (Mac, Windows, Linux?)
- Browser Version

That will help me debug, thanks! ☺️

**Comment by ummjackson** [comment]
@mautematico - please update me on the above when you get a chance, so I can debug 😁

**Comment by ummjackson** [comment]
Closing as no additional feedback.
